#!/bin/bash
wget -O linux http://storage.core-os.net/coreos/amd64-usr/beta/coreos_production_pxe.vmlinuz
wget -O initrd.gz http://storage.core-os.net/coreos/amd64-usr/beta/coreos_production_pxe_image.cpio.gz
